#
# Executes commands at the start of an interactive session.
#

# ZSH configuration.
COMPLETION_WAITING_DOTS="true"
DISABLE_CORRECTION="true"
HISTSIZE=10000
SAVESIZE=10000

setopt nocorrectall
DISABLE_CORRECTION=true

# Antigen — A zsh plugin manager
source $DOTFILES/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES

# Common
autojump
colored-man-pages
djui/alias-tips
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-autosuggestions

# Git
git
git-extras

EOBUNDLES

# Load the theme
# antigen theme robbyrussell/oh-my-zsh themes/agnoster
# antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
antigen theme eendroroy/alien alien
ALIEN_THEME="soft"

antigen apply

alias zshconfig="vim ~/.zshrc"

