# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zinit/bin/zinit.zsh

# 快速目录跳转
zinit ice lucid wait='1'
zinit light skywind3000/z.lua

zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      zdharma/fast-syntax-highlighting \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions

zinit wait lucid nocd depth=1 \
    atinit='ZSH_BASH_COMPLETIONS_FALLBACK_LAZYLOAD_DISABLE=true' \
      for 3v1n0/zsh-bash-completions-fallback

zinit ice lucid wait
zinit light zdharma/history-search-multi-word

zinit load zpm-zsh/ssh
zinit load rbirnie/oh-my-zsh-keybase
zinit load felixr/docker-zsh-completion

zinit snippet OMZ::plugins/git/git.plugin.zsh
zinit snippet OMZ::lib/completion.zsh
zinit snippet OMZ::lib/history.zsh
zinit snippet OMZ::plugins/command-not-found/command-not-found.plugin.zsh

zinit ice wait'1' lucid
zinit light laggardkernel/zsh-thefuck

zinit ice proto'git' pick'init.sh'
zinit light b4b4r07/enhancd

zinit ice depth=1; zinit load romkatv/powerlevel10k
# zinit light denysdovhan/spaceship-prompt

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias ls='lsd'
